### ISSUE TITLE
Allow volunteers to delete their data

### ISSUE THREAD

**Issue by ninsuo** [redcall-io/app#13]
We should create a way so volunteers will be able to remove their data.

Proposition:

If redecall.io receive a specific keyword (like EFFACE / REMOVE / STOP...), we desactivae the account and freeze it (in order that the next import will not overwrite him) - note: the freeze logic is already coded, it's a matter of 2 queries.

When a volunteer is called (déclenché) for the first time, redcall.io sends him another message before the one concerning the campaign to give him information about this possiblity.

**Comment by dev-mansonthomas** [comment]
If a user want to remove its account from RedCall while still beeing volunteer, he should contact his manager and have a conversation about why. The Manager would do the work.

If a user switch off email/sms notification, an email should be sent to the users of its UL.
So that the manager can contact the volunteer and have an explanation of his choice.

**Comment by ninsuo** [comment]
Commented in the code but done, closing this.
